title: "Thunder's Puppy Training Guide"
description: "A comprehensive guide for raising and training a Pomeranian puppy"
baseurl: "/thunder"
url: "https://arriw.github.io/thunder"

# Jekyll configuration
markdown: kramdown
highlighter: rouge
theme: minima

# Include these files in the build
include:
  - "*.md"

# Plugin configuration
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation structure
header_pages:
  - index.md
  - guides/puppy-schedule.md
  - guides/week-11-12.md
  - guides/week-13-16.md
  - guides/week-17-24.md
  - guides/nighttime-guide.md
  - guides/command-vocabulary.md
  - guides/barking-suppression.md

# BELOW: add site-wide defaults to unify format of guide pages
defaults:
  - scope:
      path: "guides"   # apply only to markdown files inside the guides folder
      type: "pages"
    values:
      layout: page
      permalink: "/:basename/" 